# For redundant CNN model
BATCH_SIZE = 1
IN_CHANNELS = 3
HIDDEN_CHANNELS = 8
OUT_CHANNELS = 8
KERNEL_SIZE = 3
BN_CHANNELS = HIDDEN_CHANNELS
INPUT_HEIGHT = 14
INPUT_WIDTH = 14
FLATTENED_SIZE = BATCH_SIZE*(INPUT_HEIGHT-4)*(INPUT_WIDTH-4)*OUT_CHANNELS
LINEAR_HIDDEN = 300
LINEAR_OUTPUT = 50